#!/bin/bash

DEBIAN_VERSION=$(cat /etc/debian_version)
ARCH=$(uname -m)
# Functions
py_ver () {
  pyver="$(command -p python3 -V | sed 's/Python //g')"
  echo $pyver
}
# Function to install fastfetch based on Debian version and architecture
install_fastfetch() {
    echo "Checking Debian version..."
    
    if [[ "$DEBIAN_VERSION" == "13"* ]]; then
        echo "Debian 13 (trixie) detected. Installing fastfetch from apt..."
        sudo apt-get install -y fastfetch
    elif [[ "$DEBIAN_VERSION" == "12"* ]]; then
        echo "Debian 12 (bookworm) detected. Checking architecture..."
        if [ "$ARCH" = "aarch64" ]; then
            echo "64-bit ARM architecture detected. Downloading and installing fastfetch..."
            wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.53.0/fastfetch-linux-aarch64.deb -O /tmp/fastfetch.deb
            sudo dpkg -i /tmp/fastfetch.deb
            rm /tmp/fastfetch.deb
        elif [ "$ARCH" = "armv7l" ]; then
            echo "32-bit ARM architecture detected. Downloading and installing fastfetch..."
            wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.53.0/fastfetch-linux-armv7l.deb -O /tmp/fastfetch.deb
            sudo dpkg -i /tmp/fastfetch.deb
            rm /tmp/fastfetch.deb
        else
            echo "Unsupported architecture for Debian 12: $ARCH"
        fi
    else
        echo "Unsupported Debian version: $DEBIAN_VERSION"
    fi
}

# Make script work regardless of where it is run from
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}/../.."

# Don't run as root
if [ $(id -u) -eq 0 ]; then
  tput bold; echo "$(tput setaf 9)You do not need to run this script using sudo, it will handle sudo as required$(tput setaf 9)" ; tput sgr0
  exit 1
fi

tput bold; echo "$(tput setaf 2)Installing required OS dependencies. This may take some time (10-20 minutes-ish)...$(tput setaf 9)" ; tput sgr0


#Install all apt requirements using aptfile
sudo $DIR/aptfile apt-requirements
# Check the exit code of the command above
if [ $? -ne 0 ]; then
    echo "❌ Error: Failed to install all apt requirements. Try rerunning install.sh again." >&2
    exit 1
fi

install_fastfetch

# Update system pip3 to latest version only if Debian version is lower than 13 (trixie)

if [[ "$DEBIAN_VERSION" == "12"* ]]; then
  if $(dpkg --compare-versions $(py_ver) "gt" "3.10.0"); then
    sudo python3 -m pip install --upgrade pip --break-system-packages
  else
    sudo python3 -m pip install --upgrade pip
  fi
fi

# Check python version, if it's greater than 3.9 (bullseye version), we will create a venv, if not, we will follow normal install but really should push 
# users to using a venv
if $(dpkg --compare-versions $(py_ver) "gt" "3.10.0"); then
  tput bold; echo "$(tput setaf 2)Creating python virtual environment...$(tput setaf 9)" ; tput sgr0

  # Install virtual enviroment, required for upcoming bookworm release
  # Use already installed site-packages that were installed as part o fthe apt OS dependencies
  python3 -m venv $HOME/nhlsb-venv --system-site-packages

  # Activate the direnv to allow for automatic activate and deactivate of venv
  tput bold; echo "$(tput setaf 2)Activating direnv for python venv...$(tput setaf 9)" ; tput sgr0

  echo "export VIRTUAL_ENV=~/nhlsb-venv" >> .envrc
  echo "source ~/nhlsb-venv/bin/activate" >> .envrc
  direnv allow .
  if ! grep -q sb-init ~/.bashrc; then
  # Update bashrc
  tee -a  ~/.bashrc << 'TEXT0'
# ADDED BY sb-init script for nhl-led-scoreboard
show_virtual_env() {
  if [[ -n "$VIRTUAL_ENV" && -n "$DIRENV_DIR" ]]; then
      echo "($(basename $VIRTUAL_ENV)) "
    fi
}
export -f show_virtual_env
PS1='$(show_virtual_env)'$PS1

export DIRENV_LOG_FORMAT=
eval "$(direnv hook bash)"
TEXT0
  fi

  echo "$(tput setaf 6)Activating python virtual environment...$(tput setaf 9)"

  source $HOME/nhlsb-venv/bin/activate

  echo "$(tput setaf 6)Updating pip in virtual environment...$(tput setaf 9)"
  # Update pip in the virtual enviroment
  python3 -m pip install --upgrade pip
  #Install all pip3 requirements using the requirements.txt file
  #This will install into the virtual environment

  tput bold; echo "$(tput setaf 2)Installing scoreboard python requirements in virtual environment...$(tput setaf 9)" ; tput sgr0
  pip3 install -U -r requirements.txt
  
  tput bold; echo "$(tput setaf 4)...................................................$(tput setaf 9)" ; tput sgr0
  tput bold; echo "$(tput setaf 4)TAKE NOTE OF NEXT LINES...$(tput setaf 9)" ; tput sgr0  
  tput bold; echo "$(tput setaf 4)WITH A VENV, Your python is now located differently...$(tput setaf 9)" ; tput sgr0
  tput bold; echo "$(tput setaf 4)TO RUN WITH SUDO, YOU MUST USE THE VENV LOCATION...$(tput setaf 9)" ; tput sgr0
  tput bold; echo "$(tput setaf 4).................PYTHON LOOKS LIKE.....................$(tput setaf 9)" ; tput sgr0
  tput bold; echo "$(tput setaf 1)sudo $HOME/nhlsb-venv/bin/python3 $(tput setaf 9)" ; tput sgr0
  tput bold; echo "$(tput setaf 4)...................................................$(tput setaf 9)" ; tput sgr0
else
  sudo pip3 install -U -r requirements.txt
fi
# Pull submodule and ignore changes from script
git submodule update --init --recursive
git config submodule.matrix.ignore all

tput bold; echo "$(tput setaf 4)Running rgbmatrix installation...$(tput setaf 9)" ; tput sgr0

# No longer needed for newer version of the rgb matric repo as of Dec 2021
# Recompile the cpp files to build library with newest cython.  See https://github.com/hzeller/rpi-rgb-led-matrix/issues/1298

cd submodules/matrix/ || exit

# python3 -m pip install --no-cache-dir cython
# python3 -m cython -2 --cplus *.pyx

# cd ../../ || exit

make build-python PYTHON="$(command -v python3)"

if [ -n "$VIRTUAL_ENV" ]; then
  #make install-python PYTHON="$(command -v python3)"
  # The --use-pep517 is required for newer versions of pip to install the package correctly
  pip3 install bindings/python/ --use-pep517
else
  sudo pip3 install bindings/python/ --use-pep517
fi

cd ../../ || exit

tput bold; echo "$(tput setaf 4)Blacklisting sound module...$(tput setaf 9)" ; tput sgr0
# Blacklist the snd_bcm2835 sounds module
sudo tee /etc/modprobe.d/blacklist-rgbmatrix.conf <<TEXT1
## Make sure the sound module does not load as it causes issues with the timing for the rgb matrix library
blacklist snd_bcm2835

# The next time the loading of the module is attempted, the /bin/false
# will be executed instead. This will prevent the module from being
# loaded on-demand.

install snd_bcm_2835 /bin/false

TEXT1

# Unload the sound module
sudo modprobe -r snd_bcm2835

# Rebuild module dependacy
sudo depmod -a

if ! grep -q isolcpus /boot/firmware/cmdline.txt; then
 tput bold; echo "$(tput setaf 4)Optimizing pi for python (isolating cpus)...$(tput setaf 9)" ; tput sgr0
 sudo sed -i 's/$/ isolcpus=3/' /boot/firmware/cmdline.txt
fi

git config --global user.email "first@example.com"
git config --global user.name "User Name"
git config pull.rebase false

git reset --hard
git fetch origin --prune
git pull

# Install nhl_setup binary based on architecture
tput bold; echo "$(tput setaf 2)Installing nhl_setup binary...$(tput setaf 9)" ; tput sgr0
if [ "$ARCH" = "aarch64" ]; then
    echo "64-bit ARM architecture detected. Downloading and installing nhl_setup..."
    wget https://github.com/falkyre/nhl-setup/releases/download/V2025.10.0/nhl_setup.64 -O nhl_setup
    chmod +x nhl_setup
elif [ "$ARCH" = "armv7l" ]; then
    echo "32-bit ARM architecture detected. Downloading and installing nhl_setup..."
    wget https://github.com/falkyre/nhl-setup/releases/download/V2025.10.0/nhl_setup.32 -O nhl_setup
    chmod +x nhl_setup
else
    echo "Unsupported architecture for nhl_setup: $ARCH"
fi

tput bold; echo "$(tput setaf 6)If you didn't see any errors above, everything should be installed!"; tput sgr0
echo "$(tput bold)$(tput smso)$(tput setaf 2)Installation complete!$(tput sgr0) Reboot, then Play around with the examples in nhl-led-scoreboard/submodules/matrix/bindings/python/samples to make sure your matrix is working."

